version: '3.7'
services:
  caddy:
    image: "caddy:2.0.0-alpine"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./caddy_data:/data"
