version: '3.7'
services:

  caddy:
    image: "caddy:2.3.0-alpine"
    restart: always
    networks:
      - www
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./caddy_data:/data"

  caddyfile-docker-gen:
    build:
      context: .
    restart: always
    networks:
      - www
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./Caddyfile:/etc/caddy/Caddyfile"
    environment:
      CADDY_IMAGE: "caddy"
      LABEL_PREFIX: "caddy"
      CADDYFILE_PATH: "/etc/caddy/Caddyfile"

networks:
  www:
    external: true
